baseURL= "https://codeklutz.com"
title = "Codeklutz"
paginate = 7
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-3JJ1TEHZ1S"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Codeklutz"
description = "CodeKlutz : My Developer journey & learnings"
keywords = [ "Blog", "Portfolio", "PaperMod", "TechBlog" ]
author = "Shweta Kadam"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
ShowFullTextinRSS=true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true
favicon = "/cat.gif"

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "/cat.gif"
  apple_touch_icon = "/cat.gif"
  safari_pinned_tab = "/cat.gif"

  [params.label]
  text = "CodeKlutz"
  icon = "/cat.gif"
  iconHeight = 40


  [params.profileMode]
  enabled = true
  title = "CodeKlutz"
  subtitle = "Tech blog by Shweta Kadam"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

    [[params.profileMode.buttons]]
    name = "Search"
    url = "search"

    [[params.profileMode.buttons]]
     name = "Archive"
     url = "archives"

     [[params.profileMode.buttons]]
     name = "Github"
     url = "https://github.com/"


  [params.homeInfoParams]
  Title = "Shweta Kadam"
  Content = "Fixing more things than I break, creating new things that don't break as often! <img src='https://codeklutz.com/cat.gif'>"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/shwetarkadam"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/ShwetaRKadam"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://techhub.social/@tomoko"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com"


  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/shweta-kadam-81404512a/"

  [[params.socialIcons]]
  name = "rss"
  url = "https://codeklutz.com/index.xml"


[params.analytics.google]
SiteVerificationTag = "G-3JJ1TEHZ1S"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/myblog/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "Notes Digital Hub"
name = "Notes Digital Hub"
url = "https://notes.codeklutz.com"
weight = 30

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "archives"
weight = 5


[[menu.main]]
identifier = "search"
name = "Search"
url = "search"

[markup.highlight]
noClasses = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]
