name: Deploy website

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Clone Org-mode exporter
      run: git clone https://github.com/kaushalmodi/ox-hugo.git ox-hugo

    - name: Setup emacs
      uses: purcell/setup-emacs@master
      with:
        version: 28.1

    - name: Add ox-hugo directory to load-path
      run: emacs --batch --eval="(add-to-list 'load-path \"./ox-hugo\") && (require 'ox-hugo)"
      
#     - name: Cd into the directory
#       run: cd "$(pwd)/ox-hugo"
      
#     - name: echo directory
#       run: echo "$(pwd)/ox-hugo"

#     - name: Load ox-hugo package
#       run: emacs --batch --eval="(require 'ox-hugo)"

    - name: Clone Org-mode exporter
      run: git clone https://github.com/kaushalmodi/tomelr tomelr

    - name: Export Org file to Markdown
      run: emacs ./config.org --batch -L tomelr -L ./ox-hugo -L ox-hugo.el --eval='(org-hugo-export-wim-to-md t)' --kill
      
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify --theme=hugo-papermod

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: ./public
        cname: blog.codeklutz.com
